require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - vendor/bundle/**/*
    - 'node_modules/**/*'
        
Metrics/BlockLength:
  Exclude:
    - config/**/*
    - 'spec/**/*'
    - 'vendor/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

Lint/SuppressedException:
  Exclude:
    - 'Rakefile'
