require: rubocop-rspec

RSpec/FilePath:
  Exclude:
    - spec/my_poorly_named_spec_file.rb

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'vendor/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120