require:
  - rubocop-rspec
  - rubocop-rails


AllCops:
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'bin/{rails,rake}'
    - 'node_modules/**/*'
    - 'spec/rails_helper.rb'
    - 'Gemfile'

Layout/BlockLength:
  Exclude:
    - config/**/*
    - 'spec/**/*'
    - 'vendor/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Layout/Documentation:
  Enabled: false

Layout/Encoding:
  Enabled: false

Layout/FrozenStringLiteralComment:
  Enabled: false
