version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache-v1-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-
      - run:
          name: Install dependencies
          command: |
            gem install bundler -v 2.2.3
            bundle install
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            sudo apt-get update
            sudo apt-get install yarn -y 
            yarn install
      - save_cache:
          key: gem-cache-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Run rubocop
          command: bundle exec rubocop
      - run:
          name: Run fasterer
          command: bundle exec fasterer
      - run:
          name: Run tests
          command: bundle exec rspec
      - run:
          name: Run brakeman
          command: bundle exec brakeman --exit-on-warn -f plain --quiet
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: test-results 