version: 2.1

executors:
  default:
    working_directory: ~/repo
    description: The official CircleCI Ruby Docker image
    docker:
      - image: circleci/ruby:3.0.0

      - image: postgres:9.6-jessie
        auth:
          username: skoomer
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: skoomer
          POSTGRES_DB: bookstore_development
    steps:
      - checkout
      - run:
          name: Install Ruby Dependencies
          command: bundle install
      - run: 
          name: Set up DB
          command: |
            bundle exec rake db:create db:schema:load --trace
            bundle exec rake db:migrate
        environment:
          DATABASE_URL: "postgres://skoomer@localhost:5432/bookstore_development"
      

caches:
  - &bundle_cache_full v2-repo-{{ checksum "Gemfile.lock" }}
  - &bundle_cache v2-repo-

commands:
  defaults:
    steps:
      - checkout
      - restore_cache:
          keys:
            - *bundle_cache
      - run: bundle install --path vendor/bundle
      

      - save_cache:
          key: *bundle_cache_full
          paths:
            - vendor/bundle

  run_linters:
    description: command to start linters
    steps:
      - run:
          name: rubocop
          command: bundle exec rubocop --require rubocop-rspec
  run_specs:
    steps:
      - run:
          name: run_specs
          command: bundle exec rspec --format progress spec

      - store_artifacts:
          path: ~/repo/coverage
          destination: coverage

jobs:
  lintering:
    executor: default
    steps:
      - defaults
      - run_linters
  run_specs:
    executor: default
    parallelism: 2
    steps:
      - defaults
      - run_specs

workflows:
  version: 2.1
  build:
    jobs:
      - lintering
      - run_specs:
          requires:
            - lintering