default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= Rails.application.credentials.dig(:db, :username) %>
  password: <%= Rails.application.credentials.dig(:db, :password) %>

development:
  <<: *default
  database: bookstore_development

test:
  <<: *default
  username: <%= Rails.application.credentials.dig(:db, :username) %> # => skoomer
  password: <%= Rails.application.credentials.dig(:db, :password) %> # => postgres
  database: bookstore_test

production:
  <<: *default
  database: bookstore_production
